### ISSUE TITLE
Missing dependencies when pip install

### ISSUE THREAD

**Issue by johko** [dstackai/dstack#5] opened 2020-10-13 08:49 UTC
Hey,

I just tried to install your dstack package via 'pip install' but came across three missing modules (which I then installed myself). 
Namely: tqdm, pyyaml and requests
You might want to check your package configuration to include them, so they can be installed automatically.

**Comment by peterschmidt85** [comment] 2020-10-13 09:18
@johko You're right.
We actually are still looking for a way to fix this. We tried many things but nothing seems to fix this issue! Do you have any idea how this can be fixed or workarounded?
Please check [https://github.com/dstackai/dstack-py/blob/master/setup.py](https://github.com/dstackai/dstack-py/blob/master/setup.py) and suggest if you see something wrong in our configuration.

**Comment by johko** [comment] 2020-10-19 12:06
@peterschmidt85  Thanks for the quick response (and sorry for my late). Actually I'm not really familiar with that topic myself, but may give it a shot when I have some time ;)

I guess it is a good idea to leave the issue open until it is really solved, in case somebody who knows about it better comes along.

**Comment by peterschmidt85** [comment] 2020-11-04 12:56
The issue is fixed with dstack-0.5.1 released just now. Please update and let me know if everything works now for you!

**Closed by peterschmidt85** 2020-11-04 12:56 UTC

**Comment by johko** [comment] 2020-11-10 15:09
Working great now. Thank you 👍
