### ISSUE TITLE
before_run should be a separate bash session than run

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#78] opened 2022-07-06 13:42 UTC
For instance, any directory change in `before_run` is persisted in the main run using `file`. Example:
```
  - name: dataset
    provider: python
    requirements: requirements.txt
    before_run:
      - apt-get install -y unzip
      - mkdir -p data/amex-default-prediction
      - cd data/amex-default-prediction
      - kaggle competitions download -c amex-default-prediction
      - unzip amex-default-prediction.zip
    file: dl/datamodule.py
    artifacts:
      - data
```
This will result in an error `python: can't open file '/workflow/data/amex-default-prediction/dl/datamodule.py': [Errno 2] No such file or directory`

In general `before_run` should be its own bash session.

**Comment by peterschmidt85** [comment] 2022-09-23 10:08
I will close it for now, as we deprecated the `python` provider. 
Please reopen if the issue is still relevant with other providers.

**Closed as completed by peterschmidt85** 2022-09-23 10:08 UTC
