### ISSUE TITLE
[Bug]: Running images with non-root user fails

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1492] opened 2024-08-02 12:20 UTC
### Steps to reproduce

1. Run a configuration with a docker images that chages image user to non-root, e.g. `image: spark`.
2. See `Run failed with error code CONTAINER_EXITED_WITH_ERROR.`

dstack requires root privileges inside the container (e.g. `apt-get` to install `openssh-server`). If the user is non-root, the commands fail.

We could probably override the docker user with `--user root` to make it work. But this may not work with any image. Also consider alternative solutions.

### dstack version

master

**Comment by jvstme** [comment] 2024-08-02 13:14
Possible duplicate of #1091

**Comment by r4victor** [comment] 2024-08-05 04:25
A related issue is that in such a case when dstack docker commands error (before running user commands), the run fails with no error message only showing CONTAINER_EXITED_WITH_ERROR error code:

```
Submit a new run? [y/n]: y
gentle-goat-1 provisioning completed (terminating)
Run failed with error code CONTAINER_EXITED_WITH_ERROR.
Error: 
Check CLI and server logs for more details.
```

The user has to connect to the instance and see the container logs to see why the run failed.

**Closed as completed** 2024-08-05 09:43 UTC
Labels: bug
