### ISSUE TITLE
Handle properly out-of-memory errors

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#81] opened 2022-07-08 12:52 UTC
Sometimes when dstack job runs and then dies - it shows no sign. I suspect this happens when process is terminated externally, e.g. out of memory. Show the exit code (1 or 0) similar to kubernetes events when a container/job is terminated. This helps debugging

**Comment by peterschmidt85** [comment] 2022-09-23 10:01
Currently, exit codes do get into the logs.
One issue that I'm certainly aware of is not correctly handling the case when the runner crashes because of an out-of-memory issue.

Steps to reproduce:
1. Run a workflow that quickly consumes the entire machine's memory
Expectation:
1. The run is marked as Failed
2. The cloud instance is destroyed
3. There is an error in the log
Actual:
1. The cloud instance is not destroyed (perhaps because the runner crashed)
2. There is no error in the log (perhaps the runner crashed)

I renamed the issue accordingly.

If there are other problems, let's submit separate issues with detailed steps to reproduce.

**Comment by r4victor** [comment] 2023-04-28 06:32
Container exit codes now can be viewed with `dstack ps -v` (#337).

**Closed as completed by r4victor** 2023-04-28 06:32 UTC
