### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by pranavchat14** [dstackai/dstack#803] opened 2023-12-13 19:01 UTC
### dstack version

0.12.4.post1

### Python version

3.9.16 & 3.11.6

### Host OS

macOS 13.0

### Host Arch

arm64

### What happened?

TypeError when running dstack run command to get spot-instances of GPU.

### CLI logs

```shell
Command:
`(my_tf_env) pranav@Pranav-Chaturvedi gpt % dstack run . --gpu 24GB --spot-auto -f /Users/nc24052_pranav/Downloads/gpt/.dstack.yml`


Response:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/dstack", line 5, in <module>
    from dstack._internal.cli.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/cli/main.py", line 5, in <module>
    from dstack._internal.cli.commands.config import ConfigCommand
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/cli/commands/__init__.py", line 8, in <module>
    import dstack._internal.core.services.api_client as api_client_service
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/services/api_client.py", line 3, in <module>
    import dstack._internal.core.services.configs as configs
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/services/configs/__init__.py", line 11, in <module>
    from dstack._internal.core.models.config import GlobalConfig, ProjectConfig, RepoConfig
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/config.py", line 5, in <module>
    from dstack._internal.core.models.repos.base import RepoType
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/repos/__init__.py", line 12, in <module>
    from dstack._internal.core.models.repos.virtual import VirtualRepoInfo, VirtualRunRepoData
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/repos/virtual.py", line 12, in <module>
    class VirtualRepoInfo(BaseRepoInfo):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```
```


### Server logs

```shell
File "/Library/Frameworks/Python.framework/Versions/3.8/bin/dstack", line 5, in <module>
    from dstack._internal.cli.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/cli/main.py", line 5, in <module>
    from dstack._internal.cli.commands.config import ConfigCommand
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/cli/commands/__init__.py", line 8, in <module>
    import dstack._internal.core.services.api_client as api_client_service
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/services/api_client.py", line 3, in <module>
    import dstack._internal.core.services.configs as configs
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/services/configs/__init__.py", line 11, in <module>
    from dstack._internal.core.models.config import GlobalConfig, ProjectConfig, RepoConfig
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/config.py", line 5, in <module>
    from dstack._internal.core.models.repos.base import RepoType
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/repos/__init__.py", line 12, in <module>
    from dstack._internal.core.models.repos.virtual import VirtualRepoInfo, VirtualRunRepoData
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/repos/virtual.py", line 12, in <module>
    class VirtualRepoInfo(BaseRepoInfo):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

### Runner logs

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/dstack", line 5, in <module>
    from dstack._internal.cli.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/cli/main.py", line 5, in <module>
    from dstack._internal.cli.commands.config import ConfigCommand
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/cli/commands/__init__.py", line 8, in <module>
    import dstack._internal.core.services.api_client as api_client_service
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/services/api_client.py", line 3, in <module>
    import dstack._internal.core.services.configs as configs
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/services/configs/__init__.py", line 11, in <module>
    from dstack._internal.core.models.config import GlobalConfig, ProjectConfig, RepoConfig
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/config.py", line 5, in <module>
    from dstack._internal.core.models.repos.base import RepoType
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/repos/__init__.py", line 12, in <module>
    from dstack._internal.core.models.repos.virtual import VirtualRepoInfo, VirtualRunRepoData
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dstack/_internal/core/models/repos/virtual.py", line 12, in <module>
    class VirtualRepoInfo(BaseRepoInfo):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

### Additional Information

Apple M1 Chip

**Comment by r4victor** [comment] 2023-12-14 11:40
@pranavchat14, I was able to reproduce and fix this problem. It's caused by https://github.com/pydantic/pydantic/issues/5821 and may occur if you have pydantic version less than 1.10.10. In the next dstack release we'll require minimum pydantic version and the problem should not occur.

To fix the problem in your current environment, consider installing newer pydantic version, e.g. `pip install pydantic==1.10.13`.

**Comment by peterschmidt85** [comment] 2023-12-15 15:28
Is fixed by https://github.com/dstackai/dstack/commit/97c41c60421827e68673534211eb5c52ac6bff18

**Closed as completed by peterschmidt85** 2023-12-15 15:28 UTC
Labels: bug
