### ISSUE TITLE
[Bug]: AWS policy permissions for Backend Configuration

### ISSUE THREAD

**Issue by Tob-iee** [dstackai/dstack#1618] opened 2024-08-25 04:45 UTC
### Steps to reproduce

I get this permission error when setting up my dev environment with the current permission policy on the documentation.
I think, it might be helpful to specify what type of access key should be created for the CLI to gain permissions in the docs.

```
[10:14:40] WARNING  dstack._internal.core.backends.aws.compute:202 Got botocore.exceptions.ClientError: An error occurred (AuthFailure.ServiceLinkedRoleCreationNotPermitted) when calling the RunInstances operation: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances. 
           WARNING  dstack._internal.server.background.tasks.process_submitted_jobs:371 job(150fc6)vscode-0-0: m5.large launch in aws/us-east-1 failed: NoCapacityError()                                                                                                       
[10:14:51] WARNING  dstack._internal.core.backends.aws.compute:202 Got botocore.exceptions.ClientError: An error occurred (AuthFailure.ServiceLinkedRoleCreationNotPermitted) when calling the RunInstances operation: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances. 
```

### dstack version

0.18.10

**Comment by peterschmidt85** [comment] 2024-08-25 10:49
Duplicate of https://github.com/dstackai/dstack/issues/886

**Closed as completed by peterschmidt85** 2024-08-25 10:49 UTC
Labels: bug
